@userID=1
@productId=1
@token = {{login.response.body.$.token}}

###

# @name login
POST {{baseUrl}}/auth/login
Content-Type: application/json

{
    "username":"admin",
    "password":"P@ssword123!"
}
###


# @name getProducts
GET {{baseUrl}}/products
?getFavorites=true
Content-Type: application/json
Authorization: Bearer {{token}}

###

# @name addProduct
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Wireless Phone Charger",
    "scrape_interval": "2 minutes",
    "description": "This is a phone charger for apple watch, phone and airpods",
    "product_url": "https://www.amazon.com/dp/B0C2BMNHW2",
    "desired_price": 16.99,
    "website": "AMAZON",
    "is_favorite": true,
    "user_id": 1
}

###

# @name addProduct2
POST {{baseUrl}}/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "name": "Airpods",
    "scrape_interval": "10 minutes",
    "description": "3rd generation airpods.",
    "product_url": "https://www.amazon.com/dp/B0D1WXVQTN",
    "desired_price": 175.99,
    "website": "AMAZON",
    "is_favorite": true,
    "user_id": 1
}